<a href="https://colab.research.google.com/github/thucuyen127/pycham/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import random

def taomatran(n): #Hàm tạo ma trận n hàng n cột
  a = np.random.randint(-10,10,(n,n))
  return a
m=int(input('m = '))
a = taomatran(m)
b = taomatran(m)
c = taomatran(m)
print('A = \n',a)
print('B = \n',b)
print('C = \n',c)
print('A + C = \n',a + c)
print('A - C = \n',a - c)
print('A * B = \n',a @ b)
print('A / C = \n',a  @ np.linalg.matrix_power(c, -1))
print('A * 5 = \n',a * 5)
print('A / 5 = \n',a / 5)
print('ma tran chuyen vi cua A:\n',np.transpose(a))


m = 3
A = 
 [[-7  2  5]
 [-3 -6  1]
 [ 8 -4  6]]
B = 
 [[ 1 -9  5]
 [ 3  7 -2]
 [ 5  9  8]]
C = 
 [[ 7  2 -3]
 [-9  9  0]
 [ 7 -4 -8]]
A + C = 
 [[  0   4   2]
 [-12   3   1]
 [ 15  -8  -2]]
A - C = 
 [[-14   0   8]
 [  6 -15   1]
 [  1   0  14]]
A * B = 
 [[ 24 122   1]
 [-16  -6   5]
 [ 26 -46  96]]
A / C = 
 [[-0.3968254   0.09876543 -0.47619048]
 [-1.0952381  -0.2962963   0.28571429]
 [ 0.79365079 -1.08641975 -1.04761905]]
A * 5 = 
 [[-35  10  25]
 [-15 -30   5]
 [ 40 -20  30]]
A / 5 = 
 [[-1.4  0.4  1. ]
 [-0.6 -1.2  0.2]
 [ 1.6 -0.8  1.2]]
ma tran chuyen vi cua A:
 [[-7 -3  8]
 [ 2 -6 -4]
 [ 5  1  6]]
